package com.galvanize;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import com.galvanize.cart.Cart;
import com.galvanize.cart.Item;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;

import static org.junit.jupiter.api.Assertions.assertNotNull;

public class AppTest {
    @Test
    public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");

    }

    @Test
    public void cartStartsEmpty(){
        //Setup
        Cart cart = new Cart();
        ArrayList<Item> expected = new ArrayList<Item>();
        int expectedSize = expected.size();

        //Execute
        ArrayList<Item> actual = cart.itemizedList();
        int actualSize = actual.size();

        //Assert
        Assertions.assertEquals( expectedSize, actualSize);
    }
}
